-- -- author: Anochili Blessing Ebele
-- -- purpose: The database should store information about books, authors, customers, orders, and order details. Here’s an overview of the database schema:
-- date: 14/10/2024